=head1 INSTALLATION AND USAGE INSTRUCTIONS

=over 4

=item * Install SQL::Catalog

 perl Makefile.PL
 make
 make test
 make install

You will need to download and install 
SQL::Statement and DBIx::AnyDBD unless you are using 
CPAN.pm which will detect them as a prereq and install them for you.

The Makefile.PL will create a configuration file in
lib/SQL/Catalog/Config.pm which SQL::Catalog will use to 
create the tables sql_catalog, sql_catalog_ft
and later to connect to the database and register SQL in these tables.

You must set the following environmental variable to the name of your
DBD driver sans C<DBD::>, e.g.:

 setenv SQL_CATALOG_DSN Pg

If you want to use the C<cache> and C<spider> methods, then you have to
configure the SQL::Catalog Cache::Cache, e.g:

 setenv SQL_CATALOG_STO Cache::FileCache 
 setenv SQL_CATALOG_OPT "namespace => 'sql_catalog', default_expires_in => 600"

=item * Copy the sql_* scripts to a place on your C<$PATH>

=item * Let 'er rip.

=back