
#
# SQL::Catalog configuration
#
# Autogenerated by Makefile.PL, do not edit!
#

    package SQL::Catalog::Config;

    $default = 'Mysql' ;

    @confs   = ('Mysql') ; 
    %param   =
	(
         'Mysql' => 
        {
         'UserName' => 'root',
         'DataSource' => 'dbi:Pg:dbname=mydb',
         'Password' => '',
         'name' => 'Mysql',
        },

	) ;

    $defaultparam = $param{'Mysql'} ;

    1 ;

